### PR TITLE
Fix indent bug

### LINKED ISSUE #666: Sometimes the position is strange when adding indent with tab key
Pressing the tab key after a line break adds an indent (4 spaces) to the previous line.

### PR DESCRIPTION
**Pull request by saitoeku3**
Fix #666 

## Why

Pressing the tab key after a line break adds an indent (4 spaces) to the previous line.

## What

- [x] Refactor handleTabKey function
- [x] Add line break if current line is blank

## Screenshot

Apr-03-2020 19-25-22

### CODE REVIEW

File: client/crowi-form.ts [hunk 1]
```diff
@@ -212,17 +212,18 @@ $(function() {
...
         } else {
           $target.selection('setPos', { start: newPos + 2, end: newPos + 2 })
         }
       } else {
         // indent
+        const isBlankLine = !currentLine?.text
         $target.selection('replace', {
           text:
-            '    ' +
+            `${isBlankLine ? '\n' : ''}    ` +
```
Comment (lightnet328) [inline client/crowi-form.ts:226]: nits:
```suggestion
            isBlankLine ? '\n' : '    ' +
```
I think this is easier to understand.
